import assert from "node:assert/strict";
import test from "node:test";
import { nativeCoachAnswer } from "../worker/native-coach.ts";

test("native MTG Coach explains a concrete recommendation and evidence contract",()=>{const answer=nativeCoachAnswer([{role:"user",content:"Why this change?"}],{game:"Magic: The Gathering",format:"Standard",deckText:"22 Mountain\n2 Expensive Spell\n36 Core Spell"});assert.match(answer,/Change:/);assert.match(answer,/Expected gain:/);assert.match(answer,/Tradeoff:/);assert.match(answer,/2500 opening hands/);assert.match(answer,/not silently rewrite/i)});
test("native Coach reviews a result as a decision question rather than hindsight",()=>{const answer=nativeCoachAnswer([{role:"user",content:"I lost my last game. Did I misplay?"}],{game:"Magic: The Gathering",deckText:"24 Mountain\n36 Spell"});assert.match(answer,/without pretending the result proves/i);assert.match(answer,/legal lines/i);assert.match(answer,/credible punishment/i)});
test("native Riftbound Coach uses its own verified-text analysis",()=>{const answer=nativeCoachAnswer([{role:"user",content:"What is this deck doing?"}],{game:"Riftbound",deckText:"3 Yasuo, Windrider\n3 Yi, Honed"});assert.match(answer,/verified text pattern/i);assert.match(answer,/five games/i);assert.match(answer,/Champion, Legend, domain/i)});
test("native Coach answers from the active evidence-backed coaching plan",()=>{const answer=nativeCoachAnswer([{role:"user",content:"What should I work on next?"}],{
  coachingDiagnosis:{playerGoal:"Better interaction",primary:{category:"construction-pressure",label:"Construction pressure",evidence:["2 exact-revision reports repeated the issue"]}},
  provingGrounds:{question:"Does interaction arrive in time?",watchFor:"The first critical turn.",nextAction:"Repeat the exact question once.",boundary:"One clue is not a verdict."},
});assert.match(answer,/Player goal: Better interaction/);assert.match(answer,/2 exact-revision reports/);assert.match(answer,/Does interaction arrive in time/);assert.match(answer,/One clue is not a verdict/)});
test("native Coach reviews the captured branch instead of asking for it again",()=>{const answer=nativeCoachAnswer([{role:"user",content:"Did I misplay last game?"}],{latestMatch:{coachDebrief:{decisionMoments:[{window:"sequencing",role:"defense",knownInformation:"Two open mana",chosenLine:"Cast my threat",alternativeLine:"Pass with interaction",observedPunishment:"They removed it"}]}}});assert.match(answer,/Cast my threat/);assert.match(answer,/Pass with interaction/);assert.match(answer,/Two open mana/);assert.match(answer,/result alone does not answer/i)});
