import assert from "node:assert/strict";
import test from "node:test";
import { evaluateStrategicActions,inferStrategicRole,reviewStrategicDecision,STRATEGIC_PARAMETERS } from "../app/strategic-reasoner.mjs";
test("infers role from clocks, board, and inevitability",()=>{assert.equal(inferStrategicRole({ownClock:3,opponentClock:7,boardAdvantage:.5,inevitability:-.2}).role,"aggressor");assert.equal(inferStrategicRole({ownClock:8,opponentClock:3,boardAdvantage:-.4,inevitability:.8}).role,"defender")});
test("scores complete lines instead of one-dimensional aggression",()=>{const result=evaluateStrategicActions({ownClock:9,opponentClock:4,inevitability:.7,uncertainty:.25,rangeExposure:.6},[{id:"race",label:"Race",pressure:1,tempo:.8,risk:.8,downside:.9,fragility:.8,evidence:.7},{id:"stabilize",label:"Stabilize",boardControl:.9,cardEconomy:.5,flexibility:.7,risk:-.4,downside:.15,evidence:.8}]);assert.equal(result.role.role,"defender");assert.equal(result.winner.id,"stabilize");assert.ok(STRATEGIC_PARAMETERS.length>=12)});
test("refuses judgment without captured alternatives",()=>assert.equal(reviewStrategicDecision({chosenId:"attack"}).status,"needs-context"));
test("counterfactual review identifies a materially stronger line",()=>{const review=reviewStrategicDecision({chosenId:"pass",state:{ownClock:3,opponentClock:8,boardAdvantage:.7,inevitability:-.4,uncertainty:.1},options:[{id:"attack",label:"Attack",pressure:1,tempo:1,terminalValue:.8,downside:.05,evidence:.9},{id:"pass",label:"Pass",flexibility:.1,cardEconomy:.1,downside:.1,evidence:.9}]});assert.equal(review.status,"review");assert.equal(review.best.id,"attack");assert.ok(review.regret>.7)});
test("discounts only the line exposed to credible hidden cards",()=>{const result=evaluateStrategicActions({ownClock:4,opponentClock:5,uncertainty:.3,opponentRange:{hiddenCards:[{card:"Punish",probability:.75},{card:"Other",probability:.1}]}},[{id:"fragile",label:"Fragile",tempo:.8,pressure:.7,fragility:1,losesTo:["Punish"],evidence:.8},{id:"robust",label:"Robust",tempo:.6,pressure:.5,fragility:.1,losesTo:["Other"],evidence:.8}]);assert.equal(result.winner.id,"robust");assert.ok(result.alternatives[0].rangeExposure>result.winner.rangeExposure)});
test("excludes lines explicitly marked illegal",()=>assert.equal(evaluateStrategicActions({},[{id:"illegal",legal:false,terminalValue:1},{id:"legal",legal:true}]).winner.id,"legal"));
