"use client";
import { useEffect, useMemo, useState } from "react";
import RIFTBOUND_CATALOG from "./riftbound-card-catalog.mjs";
import { analyzeRiftboundStrategy, validateRiftboundMainDeck } from "./riftbound-analysis.mjs";

function parse(text:string){return text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(line=>{const match=line.match(/^(\d+)\s+(.+)$/);return match?{quantity:Number(match[1]),name:match[2]}:{quantity:1,name:line};});}
function plainText(value:unknown){return String(value||"").replace(/<br\s*\/?\s*>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/\s+/g," ").trim();}

export default function RiftboundForge({coachingProfile,setCoachingProfile,coachDepth,setCoachDepth}:{coachingProfile:string;setCoachingProfile:(value:string)=>void;coachDepth:"quick"|"balanced"|"deep";setCoachDepth:(value:"quick"|"balanced"|"deep")=>void}){
  const [deckText,setDeckText]=useState("");
  const [messages,setMessages]=useState<Array<{role:"user"|"assistant";content:string}>>([{role:"assistant",content:"Welcome to the Riftbound Forge alpha. Bring me a deck concept or strategic question. I will separate verified rules from hypotheses while this forge learns its own game."}]);
  const [input,setInput]=useState(""); const [thinking,setThinking]=useState(false);
  const [questionsRemaining,setQuestionsRemaining]=useState<number|null>(null); const [questionsReset,setQuestionsReset]=useState<string|null>(null);
  useEffect(()=>{const saved=localStorage.getItem("metaforge.riftbound.deck");if(saved)setDeckText(saved)},[]);
  useEffect(()=>{localStorage.setItem("metaforge.riftbound.deck",deckText)},[deckText]);
  const rows=useMemo(()=>parse(deckText),[deckText]); const count=rows.reduce((sum,row)=>sum+row.quantity,0);
  const recognized=rows.filter(row=>RIFTBOUND_CATALOG.cards[row.name.toLocaleLowerCase()]);
  const unknown=rows.filter(row=>!RIFTBOUND_CATALOG.cards[row.name.toLocaleLowerCase()]);
  const legality=useMemo(()=>validateRiftboundMainDeck(rows,RIFTBOUND_CATALOG),[rows]);
  const strategy=useMemo(()=>analyzeRiftboundStrategy(rows,RIFTBOUND_CATALOG),[rows]);
  const verifiedFacts=useMemo(()=>recognized.slice(0,80).map(row=>{const card:any=RIFTBOUND_CATALOG.cards[row.name.toLocaleLowerCase()];return `${row.quantity} ${card.name} [${card.code}]: ${plainText(card.text?.richText?.body||card.text?.label||card.type)}`}).join("\n"),[recognized]);
  async function ask(contentOverride?:string){const content=(contentOverride??input).trim();if(!content||thinking||questionsRemaining===0)return;const next=[...messages,{role:"user" as const,content}];setMessages(next);setInput("");setThinking(true);try{const response=await fetch("/api/forge/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:next,depth:coachDepth,context:{game:"riftbound",deckName:"Riftbound alpha deck",format:"Riftbound constructed",deckText,coachingProfile,verifiedFacts}})});const result=await response.json();if(typeof result.remaining==="number")setQuestionsRemaining(result.remaining);if(result.resetAt)setQuestionsReset(result.resetAt);setMessages([...next,{role:"assistant",content:response.ok?result.answer:result.error}]);}catch{setMessages([...next,{role:"assistant",content:"The Riftbound coach could not answer yet."}]);}finally{setThinking(false)}}
  return <div className="riftbound-surface">
    <section className="rift-hero shell"><div><small>RIFTBOUND FORGE · ALPHA</small><h1>A new battlefield.<br/><em>The same player.</em></h1><p>Build, question, and test Riftbound ideas with the same Coach and Player DNA that learns how you think across MetaForge.</p></div><aside><b>R</b><span>RULES-SAFE ALPHA</span><small>Unverified mechanics are labeled—not invented.</small></aside></section>
    <section className="rift-workspace shell"><article><header><div><small>01 · VERIFIED DECK INTAKE</small><h2>Shape a Riftbound list</h2></div><button onClick={()=>setDeckText("")}>Clear workspace</button></header><textarea value={deckText} onChange={e=>setDeckText(e.target.value)} placeholder="Paste a Riftbound deck list here…"/>{rows.length>0&&<div className={`rift-catalog-status ${legality.legal?"verified":"review"}`}><b>{legality.legal?"Main Deck gate passed":`${legality.issues.length} rule check${legality.issues.length===1?"":"s"} need attention`}</b><p>{legality.issues.length?legality.issues.slice(0,3).map(issue=>issue.message).join(" "):"All 40 names and quantities pass the verified Main Deck size, catalog, and copy-limit gates."}</p><p>{legality.boundary}</p><a href={legality.source} target="_blank" rel="noreferrer">Official deckbuilding primer</a> · <a href={RIFTBOUND_CATALOG.source} target="_blank" rel="noreferrer">Official card gallery · updated {RIFTBOUND_CATALOG.updatedAt?.slice(0,10)||"recently"}</a></div>}{strategy.primary&&<div className="rift-strategy-read"><small>DETERMINISTIC STRATEGY READ</small><h3>{strategy.primary.label} is the clearest engine</h3><p>{strategy.primary.copies} recognized copies support it. {strategy.support.map(item=>`${item.copies} ${item.label}`).join(" · ")}</p><b>{strategy.pressure.title}</b><p>{strategy.pressure.detail}</p><em>TEST: {strategy.testContract}</em>{strategy.theory.length>0&&<details><summary>Forge Theory · text-fit cards to research</summary>{strategy.theory.map(card=><span key={card.code}><b>{card.name}</b><small>{card.tags.join(" · ")}</small></span>)}<p>{strategy.boundary}</p></details>}</div>}<footer><span><b>{count}</b> cards entered</span><span><b>{recognized.length}/{rows.length}</b> verified names</span><span><b>{legality.legal?"Passed":"Review"}</b> Main Deck gate</span></footer></article>
    <article className="rift-coach"><header><div><small>02 · RIFTBOUND COACH</small><h2>Interrogate the strategy</h2></div><i>SHARED PLAYER DNA</i></header><details><summary>How should Coach teach me?</summary><textarea value={coachingProfile} onChange={e=>setCoachingProfile(e.target.value)} placeholder="Your play style, goals, and how you like feedback…"/></details><div className="coach-depth rift-depth" aria-label="Answer depth"><span>ANSWER DEPTH</span>{(["quick","balanced","deep"] as const).map(depth=><button key={depth} className={coachDepth===depth?"active":""} onClick={()=>setCoachDepth(depth)}>{depth==="quick"?"Quick":depth==="balanced"?"Balanced":"Deep dive"}</button>)}</div><div className="rift-messages">{messages.map((m,i)=><p className={m.role} key={i}><b>{m.role==="user"?"YOU":"FORGE"}</b>{m.content}</p>)}{thinking&&<p className="assistant rift-thinking" role="status" aria-live="polite"><b>FORGE IS THINKING</b><span>Studying the Riftbound line<span className="thinking-dots" aria-hidden="true"><i>.</i><i>.</i><i>.</i></span></span></p>}</div><div className="rift-followups"><button onClick={()=>setInput("Restate your last answer more simply and give only the decision and next test.")}>Simplify</button><button onClick={()=>setInput("Go deeper on your last answer. Show assumptions, alternatives, and what would change your conclusion.")}>Go deeper</button><button onClick={()=>setInput("Challenge your last recommendation, then tell me whether you still stand by it.")}>Challenge it</button></div><div className="rift-compose"><textarea disabled={thinking||questionsRemaining===0} value={input} onChange={e=>setInput(e.target.value)} placeholder={thinking?"The Riftbound Forge is working…":"Ask about a deck concept, matchup plan, sequencing choice, or card role…"}/><button disabled={thinking||questionsRemaining===0||!input.trim()} onClick={()=>ask()}>{thinking?"Forging your answer…":"Ask Riftbound Forge →"}</button><small>{questionsRemaining===null?"Shared Coach allowance · founder unlimited":"Shared across MTG and Riftbound · "+questionsRemaining+" of 10 remaining"}{questionsReset?` · resets ${new Date(questionsReset).toLocaleDateString()}`:""}</small></div></article></section>
    <section className="rift-boundary shell"><small>INTELLIGENCE BOUNDARY</small><h2>One player profile. Two independent game brains.</h2><div><span><b>Shared</b>Learning style, risk posture, coaching preferences, strategic habits</span><span><b>Riftbound only</b>Cards, rules, legality, decks, Riftbound-native match evidence, metagame</span><span><b>Magic only</b>Cards, formats, MTG Arena history, mana and MTG mechanics</span></div><p>MTG Arena tracks Magic only. Arena matches never become Riftbound deck or matchup evidence.</p></section>
  </div>;
}
