import { userKey } from "./account-bench";
import { discoverOfficialLinks } from "../app/data-goblin-discovery.mjs";
interface Env{DB:D1Database;METAFORGE_FOUNDER_USER_KEY?:string}
const TARGETS=[
  {game:"mtg",url:"https://magic.wizards.com/en/news",host:"magic.wizards.com",sourceClass:"official-news"},
  {game:"riftbound",url:"https://riftbound.leagueoflegends.com/en-us/",host:"riftbound.leagueoflegends.com",sourceClass:"official-news"},
];
const id=async value=>[...new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))].map(x=>x.toString(16).padStart(2,"0")).join("").slice(0,24);
export async function runDataGoblins(env:Env,fetcher:typeof fetch=fetch){for(const target of TARGETS){const runId=await id(`${target.game}|${Date.now()}`);await env.DB.prepare("INSERT INTO data_goblin_runs (id,game,status) VALUES (?,?,?)").bind(runId,target.game,"running").run();try{const response=await fetcher(target.url,{headers:{"User-Agent":"MetaForgeResearch/1.0 (+private alpha; source discovery only)"}});if(!response.ok)throw new Error(`source returned ${response.status}`);const html=(await response.text()).slice(0,2_000_000);const links=[target.url,...discoverOfficialLinks(html,target.url,target.host)];let discovered=0;for(const url of links){const sourceId=await id(`${target.game}|${url}`);const result=await env.DB.prepare("INSERT OR IGNORE INTO data_goblin_sources (id,game,url,source_class,trust_tier,status) VALUES (?,?,?,?,?,'verified-source')").bind(sourceId,target.game,url,target.sourceClass,"official").run();discovered+=Number(result.meta?.changes||0);await env.DB.prepare("UPDATE data_goblin_sources SET last_seen_at=CURRENT_TIMESTAMP WHERE id=?").bind(sourceId).run()}await env.DB.prepare("UPDATE data_goblin_runs SET status='complete',finished_at=CURRENT_TIMESTAMP,sources_checked=?,sources_discovered=? WHERE id=?").bind(links.length,discovered,runId).run()}catch(error){await env.DB.prepare("UPDATE data_goblin_runs SET status='failed',finished_at=CURRENT_TIMESTAMP,error=? WHERE id=?").bind(String(error).slice(0,500),runId).run()}}}
export async function handleGoblinOperations(request:Request,env:Env){const key=await userKey(request);if(!key||key!==env.METAFORGE_FOUNDER_USER_KEY)return Response.json({error:"Founder access required"},{status:403});if(request.method==="POST"){await runDataGoblins(env);return Response.json({started:true})}const runs=await env.DB.prepare("SELECT * FROM data_goblin_runs ORDER BY started_at DESC LIMIT 20").all();const totals=await env.DB.prepare("SELECT game,COUNT(*) sources,MAX(last_seen_at) last_seen FROM data_goblin_sources GROUP BY game").all();return Response.json({runs:runs.results||[],totals:totals.results||[]},{headers:{"Cache-Control":"no-store"}})}
