export const NEW_ACADEMY_GUIDES = [
  {
    slug: "how-many-lands-should-a-commander-deck-have",
    thought: "I don't know how many lands to play.",
    title: "How Many Lands Should a Commander Deck Have?",
    description: "Build a land-count range from your curve, ramp, draw, colors, and commander instead of copying one universal number.",
    lead: "Most Commander decks begin testing somewhere in the mid-thirties, but the useful answer is a range—not a sacred number. Your deck's costs and early plays decide where inside that range you belong.",
    sections: [
      ["Start with what the deck must cast", "A deck full of five- and six-mana spells needs to make natural land drops longer than a deck whose plan operates at two and three mana. Commander cost matters too, especially when the deck expects to recast it after removal."],
      ["Treat ramp honestly", "Two-mana ramp helps only after you keep a hand capable of casting it. Expensive mana rocks and land-ramp spells should not be counted as replacements for the early lands that turn them on."],
      ["Check colors separately", "Thirty-six lands can still fail if they produce the wrong colors. After choosing a land range, count the sources for the earliest and most color-intensive spells you care about."],
      ["Test hands, then change one thing", "Draw repeated opening hands and record land count, color access, and the first meaningful play. If weak hands share the same failure, adjust one or two slots and test again."],
    ],
    watch: ["How often two-land hands actually reach their third land", "Whether tapped lands delay the deck's first meaningful play", "Which color is missing when a spell is stranded", "Whether flooding is real or merely one memorable game"],
    toolHref: "/tools/commander-land-calculator",
    toolLabel: "Estimate my starting land range",
  },
  {
    slug: "how-much-ramp-does-a-commander-deck-need",
    thought: "I don't know how much ramp I need.",
    title: "How Much Ramp Does a Commander Deck Need?",
    description: "Choose a ramp package based on when your deck needs extra mana, what colors it can produce, and what happens after a board wipe.",
    lead: "Ramp is useful only when it arrives before the spells it is meant to accelerate. Counting every card that can eventually make mana hides the difference between early development and late-game value.",
    sections: [
      ["Name the turn you are accelerating toward", "A four-mana commander wants a different ramp sequence than an eight-mana finisher. Identify the turn and spell that make acceleration valuable before choosing a count."],
      ["Prefer ramp that fits the first turns", "Two-mana ramp is common because it can turn a normal turn three into a four-mana turn. A three-mana rock may still be correct, but it is solving a later problem."],
      ["Count usable colors", "A colorless rock does not fix a demanding colored cost. Ramp should produce the colors the next play actually needs, not merely increase total mana."],
      ["Balance speed with resilience", "Creature ramp is fast and synergistic in some decks but vulnerable to sweepers. Land ramp is slower to interact with. Artifacts can be efficient but may disappear together."],
    ],
    watch: ["Ramp drawn after you already have enough mana", "Hands with ramp but no second land", "Mana pieces that cannot cast the next colored spell", "Games where one sweeper removes both board and mana"],
    toolHref: "/tools/commander-mana-base-analyzer",
    toolLabel: "Analyze my mana package",
  },
  {
    slug: "how-many-board-wipes-should-i-play-in-commander",
    thought: "I never know how many board wipes to play.",
    title: "How Many Board Wipes Should I Play in Commander?",
    description: "Choose sweepers from your deck's pace, recovery plan, and local games instead of treating every Commander deck alike.",
    lead: "A board wipe is not automatically good interaction. It can rescue a losing table, erase your own advantage, or buy time without helping you win. The right number depends on which of those jobs your deck needs.",
    sections: [
      ["Ask who rebuilds first", "Control and graveyard decks may recover from a wipe faster than creature decks. If your own plan takes many turns to rebuild, every symmetrical sweeper carries a larger cost."],
      ["Separate resets from answers", "A targeted spell can stop one engine without destroying everything else. Sweepers are best when several opponents develop threats faster than one-for-one interaction can contain."],
      ["Match the permanent types", "Creature-only wipes do little against artifact, enchantment, or planeswalker engines. Flexible resets cost more, so combine them with targeted coverage."],
      ["Use your games as evidence", "If boards repeatedly become unwinnable before you draw a reset, add coverage. If wipes sit dead while combo or value engines decide games, change the kind of interaction instead."],
    ],
    watch: ["Who is ahead when the wipe is cast", "How many turns you need to rebuild", "Threats the wipe cannot touch", "Whether a cheaper targeted answer would have solved the same moment"],
    toolHref: "/academy/how-much-interaction-do-i-actually-need",
    toolLabel: "Balance my interaction",
  },
  {
    slug: "how-to-fix-a-commander-mana-curve",
    thought: "My mana curve looks wrong.",
    title: "How to Fix a Commander Mana Curve",
    description: "Find the turns where your deck has too few useful plays and cut expensive cards without flattening its identity.",
    lead: "Average mana value can hide the real problem. Two decks can share the same average while one develops smoothly and the other spends its first turns waiting for a hand full of expensive cards.",
    sections: [
      ["Map meaningful plays by turn", "Count cards you are happy to cast on turns two, three, and four. Conditional interaction or synergy pieces with no target should not be treated as guaranteed early plays."],
      ["Find expensive cards competing for one turn", "A hand containing four different six-drops still casts only one of them first. Keep the finishers that convert your plan into a win and challenge redundant spectacle."],
      ["Protect the deck's identity", "Lowering the curve does not mean replacing every exciting card with a staple. Add inexpensive cards that establish your specific engine, find missing pieces, or protect the plan."],
      ["Review hidden costs", "Activated abilities, kicker, equip costs, and commanders you expect to recast all consume mana even when the printed curve looks low."],
    ],
    watch: ["The first turn you make a meaningful play", "Cards repeatedly waiting together in hand", "Turns where all available plays cost the same", "Cheap cards that advance the plan versus merely filling space"],
    toolHref: "/tools/mtg-deck-analyzer",
    toolLabel: "Analyze my deck's pressure points",
  },
  {
    slug: "how-many-mana-sources-do-i-need-in-commander",
    thought: "I have lands, but not the right colors.",
    title: "How Many Colored Mana Sources Do I Need in Commander?",
    description: "Count real colored sources for the spells you want to cast on time, including demanding early costs and multicolor commanders.",
    lead: "Land count answers how much mana you may draw. Colored-source count answers whether that mana can cast the cards in your hand. Those are related but separate deckbuilding questions.",
    sections: [
      ["Start with the spell, not the color pie", "A single green pip on turn six is easy to support. Two green pips on turn two are demanding. Count the symbols and name the turn when the spell matters."],
      ["Count only timely sources", "A tapped land can count when its timing fits, while a five-mana filter does not help cast a turn-three spell. Conditional sources need the condition to be reliable."],
      ["Check the hardest cards first", "You do not need to calculate every card. Test early double-pip spells, multicolor commanders, and cards whose failure would derail the opening sequence."],
      ["Do not let fixing destroy tempo", "Adding every possible tapped dual may improve colors while making the whole deck a turn slower. Balance access with the number of lands that can enter untapped when needed."],
    ],
    watch: ["Which pip is missing", "When a tapped source arrives one turn late", "Ramp that cannot produce the required color", "Cards whose color demands exceed their importance"],
    toolHref: "/tools/commander-color-source-calculator",
    toolLabel: "Estimate a colored-source target",
  },
  {
    slug: "how-to-balance-tokens-enablers-and-payoffs",
    thought: "My token deck makes tokens but doesn't win.",
    title: "How to Balance Token Makers, Enablers, and Payoffs",
    description: "Separate token production, multiplication, protection, and conversion so a Commander token deck works even when one piece is missing.",
    lead: "Token decks often fail from composition, not card quality. A pile of cards that mention tokens can contain too many payoffs, too few makers, or no reliable way to turn a wide board into a win.",
    sections: [
      ["Token makers are the floor", "Payoffs do nothing without bodies. Prefer makers that work independently, match the commander's incentives, and arrive before the cards that reward them."],
      ["Enablers change efficiency", "Doublers, cost reducers, and sacrifice outlets can make the engine explosive, but they need enough compatible cards around them. A generic typal payoff is not automatically token support."],
      ["Payoffs must convert the board", "Anthems, drain effects, card draw, and sacrifice value solve different problems. Include ways to turn many small objects into damage or durable advantage."],
      ["Plan for the reset", "Protection, instant-speed production, recursion, and card flow determine whether one board wipe ends the game. Do not spend every slot making the best-case board larger."],
    ],
    watch: ["Payoffs drawn without makers", "Token makers that require another setup piece", "Boards that are wide but cannot attack profitably", "How many cards remain after a sweeper"],
    toolHref: "/tools/commander-deck-checker",
    toolLabel: "Check my token deck's structure",
  },
] as const;

export function newAcademyGuideBySlug(slug: string) { return NEW_ACADEMY_GUIDES.find((guide) => guide.slug === slug); }
